Update github actions
clouddrove/github-actions pull request #5
Opened 2020-10-14 15:22 UTC by dhyanio

# Description

- Add. readme script
- Add, push script

2020-10-14 15:26 UTC, sohanyadav requested changes
check

2020-10-14 15:26 UTC, sohanyadav commented on src/push.sh
> +  git config --global user.email "ajay@clouddrove.com"
why ajay shoud be anmol

2020-10-14 15:26 UTC, sohanyadav commented on src/push.sh
> +  git add . && git commit -m "upload"
commit should be make create read me

2020-10-14 15:26 UTC, sohanyadav commented on src/terratest_go.sh
> +<<<<<<< HEAD
???????/?

2020-10-14 15:26 UTC, sohanyadav commented on src/terratest_go.sh
> +=======
???????????

2020-10-14 22:56 UTC, harmanjyotkaur requested changes

2020-10-14 22:56 UTC, harmanjyotkaur commented on src/terratest_go.sh
> +>>>>>>> bebc31ca55bce4dd0e77022d5491a10630cb8076
why we have this here ? please fix it.

2020-10-16 11:07 UTC, sohanyadav approved these changes
LGTM!!

2020-10-16 11:16 UTC, merged